### ISSUE TITLE
Trackmate XML output reports pixelated y displacement values but not x or z

### ISSUE THREAD

**Issue by ctrueden** [fiji/TrackMate#68] opened 2015-10-13 16:01 UTC
From [Fiji BugZilla issue #1165](http://fiji.sc/bugzilla/show_bug.cgi?id=1165):
> When using Trackmate to track fluorescent particles, the output results sent to XML do not make sense, despite being checked over several raw fluorescence datasets. The displacements between timepoints for the X and Z components of the tracks appear approximately gaussian-distributed, as I would expect, but the Y components are concentrated in small peaks centered on integral pixel displacements. Is it possible to make sure that the particle detection and output generation for these two components are the same? 
>
> My pixel dimensions are isotropic, I am using the LoG detector option (no median filtering, subpixel localization=on), and the LAP tracker (no gap closing). 
> I have run this with the same result on both processed and unprocessed image stacks, so I know this is not an artifact of the image processing.

**Comment by tinevez** [comment] 2015-10-15 07:25
I have been in contact with the user and could confirm it on her data. 
Using synthetic 2D data, I could *not* reproduce it. It seems like it happens for 3D solely. 
I did quite some extensive tests on it and could not corner the reason behind this bug properly yet. I copy below the state of our discussions.

**Comment by tinevez** [comment] 2015-10-15 07:26
I guess the problem is not with the LoG detector itself (that's the part that generates integer pixels) but the subpixel localizer:
More precisely, the class called at this line

https://github.com/fiji/TrackMate/blob/master/src/main/java/fiji/plugin/trackmate/detection/DetectionUtils.java#L207

**Comment by tinevez** [comment] 2015-10-19 15:19
This is fixed with imglib/imglib2-algorithm#13.
So we just need to wait for the next release of imglib2-algorithm

**Closed** 2015-10-19 15:21 UTC
Labels: bug
