### ISSUE TITLE
"Save" button greyed 

### ISSUE THREAD

**Issue by MaximeMaW** [fiji/TrackMate#106] opened 2017-08-15 23:00 UTC
Hello,

Thanks a lot for TrackMate, I have been using it for a couple of weeks now with great success!

In particular, I find the "save" option very useful. However, sometimes, this option appears greyed out at the end of the analysis, and it will not activate even after several minutes. The "actions" panel works fine though.

After a little bit of playing around, it seems that this option greys out when a big file is opened (in my case: 100k frames, 1.2 Gio file), although I am unsure if this is the real cause.

More precisely, the Save button is available until the detection step and greyed out after it. No error message appears on the console. With smaller files (10k frames, 128 Mio), I can use the save button properly.

I am attaching the TrackMate log file, even though I see nothing special in it:

```TrackMate v3.5.1-SNAPSHOT started on:
Tue, 15 Aug 2017 15:46:26
Image data:
For the image named: 001_1000mW_25pGlycerol_1nM_1_69ms_1ms002.nd2.tif.
Matching file 001_1000mW_25pGlycerol_1nM_1_69ms_1ms002.nd2.tif in folder: /home/maxime/zlatan-primary/maxime/2017-inVitro/170809_633nm_inVitro/tiff/
Geometry:
  X =    0 -  255, dx = 0.160000
  Y =    0 -   23, dy = 0.160000
  Z =    0 -    0, dz = 1.00000
  T =    0 - 99999, dt = 1.00000
Spot feature analyzers:
 - Manual spot color analyzer provides: Spot color; is manual.
 - Spot descriptive statistics provides: Mean, Median, Min, Max, Total int., Stdev.
 - Spot radius estimator provides: Diam.
 - Spot contrast and SNR provides: Constrast, SNR.
Edge feature analyzers:
 - Edge target provides: Source ID, Target ID, Cost.
 - Edge mean location provides: T, X, Y, Z.
 - Edge velocity provides: V, D.
 - Manual edge color analyzer provides: Edge color; is manual.
Track feature analyzers:
 - Branching analyzer provides: N spots, Gaps, Longest gap, Splits, Merges, Complex.
 - Track duration provides: Duration, T start, T stop, Displacement.
 - Track index provides: Index, ID.
 - Track location provides: X, Y, Z.
 - Velocity provides: Mean V, Max V, Min V, Median V, V std.
 - TRACK_SPOT_QUALITY provides: Mean Q, Max Q, Min Q, Median Q, Q std.
Computing spot features.
Computation done in 25 ms.
Computing edge features:
  - Edge target in 0 ms.
  - Edge mean location in 0 ms.
  - Edge velocity in 0 ms.
Computation done in 0 ms.
Computing track features:
  - Branching analyzer in 0 ms.
  - Track duration in 0 ms.
  - Track index in 0 ms.
  - Track location in 0 ms.
  - Velocity in 0 ms.
  - TRACK_SPOT_QUALITY in 0 ms.
Computation done in 0 ms.
Starting detection using LoG detector
with settings:
  - target channel: 1
  - threshold: 500.0
  - do median filtering: false
  - radius: 0.24
  - do subpixel localization: true
Starting detection process using 32 threads.
Detection processes 32 frames simultaneously and allocates 1 thread per frame.
Found 255831 spots.
Detection done in 42.8 s.
Computing spot quality histogram...
Histogram calculated in 0.5 s.
Initial thresholding with a quality threshold above 0.0 ...
Starting initial filtering process.
Retained 255831 spots out of 255831.
Calculating spot features...
Computing spot features.
Computation done in 516909 ms.
Calculating features done in 516.9 s.
Performing spot filtering on the following features:
No feature threshold set, kept the 255831 spots.
Starting tracking using Simple LAP tracker
with settings:
  Linking conditions:
    - max distance: 5.0
    - no feature penalties
  Gap-closing conditions:
    - max distance: 5.0
    - max frame gap: 2
    - no feature penalties
  Track splitting not allowed.
  Track merging not allowed.
Starting tracking process.
Found 37226 tracks.
Tracking done in 21.5 s.
Computing track features:
  - Branching analyzer in 266 ms.
  - Track duration in 178 ms.
  - Track index in 30 ms.
  - Track location in 160 ms.
  - Velocity in 273 ms.
  - TRACK_SPOT_QUALITY in 257 ms.
Computation done in 1218 ms.
Performing track filtering on the following features:
Starting track filtering process.
No feature threshold set, kept the 37226 tracks.
Computing edge features:
  - Edge target in 514 ms.
  - Edge mean location in 643 ms.
  - Edge velocity in 495 ms.
Computation done in 1674 ms.
```

I am also attaching a screenshot of the latest panel, with the greyed button.

![capture du 2017-08-15 15-57-55](https://user-images.githubusercontent.com/26774320/29340257-ddb81dd2-81d2-11e7-965d-7b252eee734b.png)

I'd be happy to provide any additional information, including the problematic file(s). Thanks a lot!

I am using the latest TrackMate version packaged into Fiji: 3.5.1-SNAPSHOT.

**Comment by tinevez** [comment] 2017-08-18 18:49
Hi and thanks for your kind words. 
This is a serious problem and it will be hard to tackle. 
The log you attach here do not show any exception or error message which worries me. Nothing shows up in the imagej console? 
Also, since it seems to be correlated with the image size, could you please try to run the exact same analysis on another computer? 

Finally, I am surprised by the amount of time it took to compute the spot features  (10 minutes ). Could the step where spot features are calculated be the moment where we loose the save button?

**Comment by MaximeMaW** [comment] 2017-08-18 22:20
Hi @tinevez,

Thank you for your feedback.

As far as I can tell, nothing shows up in the ImageJ error log (if this is what you call the imageJ console), and nothing in the terminal if Fiji is started from the terminal. I will re-run this on another computer as soon as I can (probably this week-end), and check when this happens. I will keep you posted.

Thanks again for your interest in this issue.

**Comment by MaximeMaW** [comment] 2017-08-19 22:04
Hi @tinevez 

1. I tried to run the same analysis (exact same file) on a different computer (Mac OS, latest version of Fiji, TrackMate 3.5.1-SNAPSHOT), with twice as much RAM as the previous analysis. I get exactly the same results, see the log attached below

2. Indeed, it seems that the button gets greyed when computing the features, and never comes back.

3. I confirm that no exception gets thrown by ImageJ (actually I tried the analysis on a third computer, with 4 GB of RAM, and here Memory errors display, either when trying to load the TIFF file, or at some point later when computing the features. This exception does not show up on the two other computers I tried, where the posted logs come from).

Any help would be much appreciated. If there is any additional manipulation I can do to provide extra information, I'd be happy to do so. 

```
TrackMate v3.5.1-SNAPSHOT started on:
Sat, 19 Aug 2017 14:45:18
Image data:
For the image named: 001_1000mW_25pGlycerol_1nM_1_69ms_1ms001.nd2.tif.
Matching file 001_1000mW_25pGlycerol_1nM_1_69ms_1ms001.nd2.tif in folder: /Volumes/PegasusPrimary/Data/maxime/2017-inVitro/170809_633nm_inVitro/tiff/
Geometry:
  X =    0 -  255, dx = 0.160000
  Y =    0 -   23, dy = 0.160000
  Z =    0 -    0, dz = 1.00000
  T =    0 - 99999, dt = 1.69000
Spot feature analyzers:
 - Manual spot color analyzer provides: Spot color; is manual.
 - Spot descriptive statistics provides: Mean, Median, Min, Max, Total int., Stdev.
 - Spot radius estimator provides: Diam.
 - Spot contrast and SNR provides: Constrast, SNR.
Edge feature analyzers:
 - Edge target provides: Source ID, Target ID, Cost.
 - Edge mean location provides: T, X, Y, Z.
 - Edge velocity provides: V, D.
 - Manual edge color analyzer provides: Edge color; is manual.
Track feature analyzers:
 - Branching analyzer provides: N spots, Gaps, Longest gap, Splits, Merges, Complex.
 - Track duration provides: Duration, T start, T stop, Displacement.
 - Track index provides: Index, ID.
 - Track location provides: X, Y, Z.
 - Velocity provides: Mean V, Max V, Min V, Median V, V std.
 - TRACK_SPOT_QUALITY provides: Mean Q, Max Q, Min Q, Median Q, Q std.
Computing spot features.
Computation done in 54 ms.
Computing edge features:
  - Edge target in 0 ms.
  - Edge mean location in 0 ms.
  - Edge velocity in 0 ms.
Computation done in 0 ms.
Computing track features:
  - Branching analyzer in 0 ms.
  - Track duration in 0 ms.
  - Track index in 0 ms.
  - Track location in 0 ms.
  - Velocity in 0 ms.
  - TRACK_SPOT_QUALITY in 0 ms.
Computation done in 0 ms.
Starting detection using LoG detector
with settings:
  - target channel: 1
  - threshold: 600.0
  - do median filtering: false
  - radius: 0.24
  - do subpixel localization: true
Starting detection process using 24 threads.
Detection processes 24 frames simultaneously and allocates 1 thread per frame.
Found 153370 spots.
Detection done in 65.5 s.
Computing spot quality histogram...
Histogram calculated in 0.4 s.
Initial thresholding with a quality threshold above 0.0 ...
Starting initial filtering process.
Retained 153370 spots out of 153370.
Calculating spot features...
Computing spot features.
Computation done in 330593 ms.
Calculating features done in 330.6 s.
Performing spot filtering on the following features:
No feature threshold set, kept the 153370 spots.
Starting tracking using Simple LAP tracker
with settings:
  Linking conditions:
    - max distance: 2.0
    - no feature penalties
  Gap-closing conditions:
    - max distance: 2.0
    - max frame gap: 2
    - no feature penalties
  Track splitting not allowed.
  Track merging not allowed.
Starting tracking process.
Found 29620 tracks.
Tracking done in 5.9 s.
Computing track features:
  - Branching analyzer in 127 ms.
  - Track duration in 63 ms.
  - Track index in 17 ms.
  - Track location in 49 ms.
  - Velocity in 89 ms.
  - TRACK_SPOT_QUALITY in 96 ms.
Computation done in 526 ms.
Performing track filtering on the following features:
Starting track filtering process.
No feature threshold set, kept the 29620 tracks.
Computing edge features:
  - Edge target in 145 ms.
  - Edge mean location in 133 ms.
  - Edge velocity in 93 ms.
Computation done in 387 ms.
```

**Comment by tinevez** [comment] 2017-08-20 07:30
Ok then. 
Could you send me the image file please?

**Comment by MaximeMaW** [comment] 2017-08-21 16:02
There it is: [image file](https://cloud.biologie.ens.fr/index.php/s/WugbDL5H0NTwpCi)

**Comment by MaximeMaW** [comment] 2017-09-02 16:37
Hi @tinevez, have you been able to reproduce the issue I encounter? Let me know if I can provide any additional information.

**Comment by tinevez** [comment] 2017-09-02 21:39
Hi @MaximeMaW 
No I was NOT able to reproduce the problem. The spot calculation feature processed for as long as in your case and completed normally. I could save the data. Here it is
http://dl.pasteur.fr/fop/waxeZrGH/001_1000mW_25pGlycerol_1nM_1_69ms_1ms001.nd2.xml

I suspect only two things:

 * Did you try to show the log panel (clicking on the 'i' button) or the view control panel (the orange wrench icon) during the spot feature calculation?
 * The spot feature computation time is unusually long. I suspect a problem with the spot size. Probably setting a spot radius larger than 1 pixel is a good idea. 

Your data seem to be tricky to track, but this is another matter.

**Comment by MaximeMaW** [comment] 2017-09-03 21:09
Hi @tinevez 

Thank you very much for your time. I indeed remember trying to show the log panel. I will make another test without showing it and will tell you how it goes. Also, I totally agree that the data is tricky to track, this was one of our first experiments.

**Comment by MaximeMaW** [comment] 2017-09-03 22:36
Hi @tinevez,

I confirm that when I do NOT click the log ("i") button, I am able to save the data as expected. Thus, a **workaround** for this issue is to avoid clicking it. 

1. For my use-case, this is a valid workaround. However, if there is anything I can do to help troubleshoot the issue further let me know
2. Should I close the issue/rename it to "Save button greyed permanently when displaying log"/other?

Thanks a lot!

**Comment by tinevez** [comment] 2019-09-05 11:23
Humm I cannot reproduce the issue with current version so I am going to close it for now. 
Please reopen it if it happens for you.

**Closed by tinevez** 2019-09-05 11:23 UTC
