### ISSUE TITLE
Export to Icy

### ISSUE THREAD

**Issue by KrishnaMudumbi** [fiji/TrackMate#126] opened 2018-05-30 14:35 UTC
Hi,

I am having issues exporting my TrackMate results to Icy. Every time I try and execute the function, I get the following error:

Exception in thread "TrackMate action thread" java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1967)
	at fiji.plugin.trackmate.action.IcyTrackExporter.execute(IcyTrackExporter.java:62)
	at fiji.plugin.trackmate.gui.panels.ActionChooserPanel$1$1.run(ActionChooserPanel.java:127)

I am happy to provide any more input needed to look into the problem.

Thanks,

Krishna

**Comment by tinevez** [comment] 2019-09-05 11:20
_Investigate_

**Comment by tinevez** [comment] 2019-09-05 13:05
Ok I tested the export to Icy, and it seems to work:

![TrackMateInIcy](https://user-images.githubusercontent.com/3583203/64344277-709cc880-cfee-11e9-8327-f942460222d4.PNG)

They way I got this working was to use the `Export tracks to Icy` action in the last panel of TrackMate. It generates a new XML file that can directly be opened in the Icy TrackManager. Do not use the `Import TrackMate` action of the TrackManager with this file.

Does this work on your side?

**Comment by tinevez** [comment] 2019-09-05 13:05
Pining @KrishnaMudumbi

**Comment by tinevez** [comment] 2019-11-19 11:56
Any news? @KrishnaMudumbi 
I will close this issue for now. Please reopen if the problem appears.

**Closed by tinevez** 2019-11-19 11:56 UTC
Labels: investigate

**Comment by ShaunChristie** [comment] 2020-12-17 18:40
Hi,
I am experiencing the exact same error code as above, was there ever a specific resolution to the error? For me, this error does occur at the last panel of the Trackmate GUI when using the 'Export tracks to Icy' action. If I just attempt to load an xml file into Icy (produced by the 'Export tracks to xml file' action instead) then the error code there reads "TrackSegment : The detection must be added with consecutive T value. Detection was not added"
Thanks!

**Comment by Majahonkhe** [comment] 2021-02-13 18:46
> Hi,
> I am experiencing the exact same error code as above, was there ever a specific resolution to the error? For me, this error does occur at the last panel of the Trackmate GUI when using the 'Export tracks to Icy' action. If I just attempt to load an xml file into Icy (produced by the 'Export tracks to xml file' action instead) then the error code there reads "TrackSegment : The detection must be added with consecutive T value. Detection was not added"
> Thanks!

The 'Export tracks to Icy' error seems to be an issue with the later versions of Trackmate (v6.0.1 in my case). This export function works fine in the older version (v5.2.0).

**Comment by kmshort** [comment] 2021-06-18 05:25
I'm having this issue with TrackMate 6.0.3
```
Exception in thread "TrackMate action thread" java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1967)
	at fiji.plugin.trackmate.action.IcyTrackExporter.execute(IcyTrackExporter.java:62)
	at fiji.plugin.trackmate.gui.panels.ActionChooserPanel$1$1.run(ActionChooserPanel.java:127)
```
This happens at the final page, using "Select a action" and "Export tracks to Icy".

**Comment by tinevez** [comment] 2021-06-18 07:39
Hello.
Sorry I still cannot reproduce this bug. The export from TrackMate and the import in Icy still work.
