### ISSUE TITLE
Export tracks to Icy fails

### ISSUE THREAD

**Issue by kmshort** [fiji/TrackMate#173] opened 2021-06-18 05:38 UTC
Hi,

On the final TrackMate page, using "Select a action" and "Export tracks to Icy" throws the exception:

```
Exception in thread "TrackMate action thread" java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1967)
	at fiji.plugin.trackmate.action.IcyTrackExporter.execute(IcyTrackExporter.java:62)
	at fiji.plugin.trackmate.gui.panels.ActionChooserPanel$1$1.run(ActionChooserPanel.java:127)
```

This was previously reported, thread closed, 2 people since posted that they had the same issue and it wasn't resolved. It's still happening now.
ImageJ 1.53c, Windows. Latest Fiji version, freshly downloaded and unpacked.
TrackMate 6.0.3

thanks

**Comment by tinevez** [comment] 2021-06-18 07:42
Hello.

I could not reproduce this bug.

Can you tell me how to make it happen?

**Comment by kmshort** [comment] 2021-06-18 07:54
Download the stock Fiji windows version from the website.
Open an image sequence, convert to hyperstack, and run TrackMate.
Add the spots, generate the tracks.
Get to the end and "Select a action" and "Export tracks to Icy". It'll throw an exception.

Do you have a trial dataset we can use to see if our errors happen with that?
thanks.

**Comment by kmshort** [comment] 2021-06-18 08:02
My data is 423x387x7 (x,y,z) with 189 time points, 2 channels. The data voxel sizes are approx 0.63x0.63x4 (xyz). These are set prior to TrackMate running (using Image>Properties in ImageJ), and TrackMate6.0.3 detects the correct dimensions and pixel/voxel dimensions at the start.
Tracks are just on one channel of course.

**Comment by tinevez** [comment] 2021-06-18 08:19
ok. I suspect a bug that occurs only with some data. I tried with the default dataset and it works.
Would you be ok to send me the TrackMate XML file? I think I could debug this with just the XML.

**Comment by tinevez** [comment] 2021-06-18 09:24
@kmshort  I tested with the default dataset and could not reproduce. This is why I wish I could test with yours.

**Comment by tinevez** [comment] 2021-06-24 07:13
Hello @kmshort. Any news?

**Comment by tinevez** [comment] 2021-07-27 15:21
Closing for now.

**Closed by tinevez** 2021-07-27 15:21 UTC
Labels: investigate
